fix: update riscv-rt to avoid yanked version
Even with the changes in https://github.com/esp-rs/esp-hal/pull/350 creating a new project from the template for an esp32c3 produces a result that fails to build with:

```
error: failed to select a version for the requirement `riscv = "^0.9"`
candidate versions found which didn't match: 0.10.1, 0.8.0, 0.7.0, ...
location searched: crates.io index
required by package `riscv-rt v0.10.0`
    ... which satisfies dependency `riscv-rt = "^0.10"` of package `example_project v0.1.0 (/home/seth/Code/src/github.com/rustbox/esp-hal/example-project)`
```